site_name: VARAG
repo_url: https://github.com/adithya-s-k/VARAG
repo_name: adithya-s-k/VARAG
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: light blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Notebooks:
    - Simple RAG: simpleRAG.ipynb
    - Colpali RAG: colpaliRAG.ipynb
    - Hybrid Colpali RAG: hybridColpaliRAG.ipynb
    - Vision RAG: visionRAG.ipynb
  - Demo: demo.ipynb

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/adithya-s-k/VARAG
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/varag/

plugins:
  - search
  - mkdocs-jupyter